deploy-production:
	kubectl apply -k overlays/production

destroy-production:
	kubectl delete -k overlays/production

deploy-development:
	kubectl apply -k overlays/development

destroy-development:
	kubectl delete -k overlays/development