apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-deploy-binding
subjects:
- kind: ServiceAccount
  name: github-deploy-sa
roleRef:
  kind: Role
  name: github-deploy-role
  apiGroup: rbac.authorization.k8s.io
