# write me a simple gh actions workflow
name: Deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environmenmt:
        description: "Environment"
        required: true
        default: 'development'
        type: select
        options:
          - 'production'
          - 'development'

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      deploy-env: ${{ steps.set-output.outputs.deploy-env }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Variables for Production
      id: set-output
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
      run: echo "deploy-env=production" >> $GITHUB_ENV

    - name: Set Variables for Development
      id: set-output
      if: (github.event_name == 'push' && github.ref == 'refs/heads/develop') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
      run: echo "deploy-env=development" >> $GITHUB_ENV

    - name: Push to job output
      id: set-output
      run: echo "deploy-env=${{ env.DEPLOY_ENV }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    depends-on: ['preflight']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        uses: paulhatch/semantic-version@v5

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=your-docker-repo/gameserver:${{ needs.preflight.outputs.deploy-env }}-${{ steps.version.outputs.version }}
          docker build -t $IMAGE_NAME -f gameserver/Dockerfile .
          docker push $IMAGE_NAME