# write me a simple gh actions workflow
name: Deploy Gameserver

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'gameserver/**'
      - '.github/workflows/deploy-gameserver.yaml'
      - 'infrastructure/k8s/gameserver/**'
  workflow_dispatch:
    inputs:
      environmenmt:
        description: "Environment"
        required: true
        default: 'development'
        type: choice
        options:
          - 'production'
          - 'development'

jobs:
  preflight:
    runs-on: ubuntu-latest
    outputs:
      deploy-env: ${{ steps.set-output.outputs.deploy-env }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Variables for Production
      if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
      run: echo "deploy-env=production" >> $GITHUB_ENV

    - name: Set Variables for Development
      if: (github.event_name == 'push' && github.ref == 'refs/heads/develop') || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'development')
      run: echo "deploy-env=development" >> $GITHUB_ENV

    - name: Push to job output
      id: set-output
      run: echo "deploy-env=${{ env.deploy-env }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: ['preflight']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          # Optional path to check for changes. If any changes are detected in the path the
          # 'changed' output will true. Enter multiple paths separated by spaces.
          change_path: "gameserver"
          # Named version, will be used as suffix for name version tag
          namespace: gameserver
          bump_each_commit: true
          enable_prerelease_mode: true
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=lvl13mage/steamsnstreams_gameserver:${{ needs.preflight.outputs.deploy-env }}-${{ steps.version.outputs.version }}
          docker build -t $IMAGE_NAME -f gameserver/Dockerfile gameserver
          docker push $IMAGE_NAME